/**
  * This class will use STB to load images
*/

#include "ImageLoader.h"
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>

//Loads and return image data from given path
unsigned char* ImageLoader::loadImage(std::string path){

	unsigned char* image = stbi_load(path.c_str(), &width, &height, 0, STBI_rgb);
  return image;
}

//Frees the specificed image data
void ImageLoader::freeData(unsigned char* data){
  stbi_image_free(data);
}

//Return the width generated by loading the image
int ImageLoader::returnWidth(){
	return width;
}

//Returns the height generated by loading image
int ImageLoader::returnHeight(){
	return height;
}